import type { Product } from '../types'

export const PRODUCTS: Product[] = [
  {
    id: 'let-go',
    name: 'Let Go',
    emotion: 'Release',
    fragrance: 'Strawberry Guava · Coconut Lime · Verbena',
    description: 'Some things are meant to be released.',
    long_description: 'Sweet strawberry guava, coconut lime, and verbena create a bright, airy fragrance that feels light, freeing, and full of possibility.',
    price: 35,
    image_url: '/products/let-go.webp',
    badge: 'Release',
    burn_time: '35–45 hrs',
    wax: 'Coconut-Soy Wax Blend',
    size: '7 oz / 198g',
    for_text: 'For anyone holding on to something heavy — a feeling, a relationship, a version of themselves that no longer serves them.',
  },
  {
    id: 'im-safe',
    name: "I'm Safe",
    emotion: 'Safety',
    fragrance: 'Sea Salt · Orchid · Magnolia Peony',
    description: 'A calming ritual for moments when you need to exhale.',
    long_description: 'Soft orchid, sea salt, magnolia, and peony come together in a delicate fragrance that feels peaceful, clean, and grounding.',
    price: 35,
    image_url: '/products/im-safe.webp',
    badge: 'Safety',
    burn_time: '35–45 hrs',
    wax: 'Coconut-Soy Wax Blend',
    size: '7 oz / 198g',
    for_text: 'For the moments you need to feel safe, grounded, and at peace.',
  },
  {
    id: 'you-are-enough',
    name: 'You Are Enough',
    emotion: 'Self-Worth',
    fragrance: 'Papaya Paradise · Mango',
    description: 'A gentle reminder to slow down and be kind to yourself.',
    long_description: 'Juicy papaya and ripe mango blend into a warm, comforting fragrance that brings a touch of sunshine into any space.',
    price: 35,
    image_url: '/products/you-are-enough.webp',
    badge: 'Self-Worth',
    burn_time: '35–45 hrs',
    wax: 'Coconut-Soy Wax Blend',
    size: '7 oz / 198g',
    for_text: 'For moments of self-doubt, comparison, or exhaustion. For the nights you forget your own worth.',
  },
  {
    id: 'new-beginning',
    name: 'New Beginning',
    emotion: 'Renewal',
    fragrance: 'Lemongrass Lime · Garden Mint',
    description: 'A fresh start in a candle.',
    long_description: 'Bright notes of lemongrass, lime, and garden mint create a clean, uplifting scent that feels like opening the windows on a new day.',
    price: 35,
    image_url: '/products/new-beginning.webp',
    badge: 'Renewal',
    burn_time: '35–45 hrs',
    wax: 'Coconut-Soy Wax Blend',
    size: '7 oz / 198g',
    for_text: 'For new chapters, new homes, new mindsets. For anyone who has closed a door and is ready to open the next one.',
  },
]

export const CANDLE_CARE = [
  'Trim the wick to 1/4" before each burn.',
  'Allow the wax to melt evenly across the surface during the first burn.',
  'Never leave a burning candle unattended.',
  'Keep away from children, pets, and flammable objects.',
  'Discontinue use when 1/2" of wax remains.',
]

export const PRODUCT_DETAILS = [
  { label: 'Size', value: '7 oz / 198 g' },
  { label: 'Wax', value: 'Coconut-Soy Wax Blend' },
  { label: 'Wick', value: 'Wooden Wick' },
  { label: 'Made', value: 'Hand-Poured in Small Batches' },
  { label: 'Burn Time', value: 'Approx. 35–45 Hours' },
]
