import type { Product } from '../types'

export const PRODUCTS: Product[] = [
  {
    id: '0',
    name: 'Let Go',
    emotion: 'Release',
    fragrance: 'Strawberry Guava · Coconut Lime',
    description: 'A tropical-soft candle created to help you release, reset, and breathe again. This scent opens with fresh guava and ripe strawberry, softened by a coconut-lime base that dissolves tension and invites stillness.',
    price: 35,
    image_url: '',
    badge: 'Release',
    burn_time: '~45–55 hrs',
    wax: 'Premium Blend',
    size: '7 oz / 198g',
    for_text: 'For anyone holding on to something heavy — a feeling, a relationship, a version of themselves that no longer serves them.',
    care_notes: 'After a long day. In a bath. During journaling. Whenever you need permission to exhale.',
  },
  {
    id: '1',
    name: 'I Am Sage',
    emotion: 'Clarity',
    fragrance: 'Sea Salt Orchid · Magnolia Peony',
    description: 'A clean floral-mineral scent for clarity, softness, and quiet power. Crisp sea salt grounds the blooming orchid and magnolia — a scent that feels like knowing exactly who you are.',
    price: 35,
    image_url: '',
    badge: 'Clarity',
    burn_time: '~45–55 hrs',
    wax: 'Premium Blend',
    size: '7 oz / 198g',
    for_text: 'For the woman returning to herself. For quiet confidence, clear thinking, and stepping into your own truth without apology.',
    care_notes: 'Morning rituals, meditation, creative work, or any moment that calls for presence and power.',
  },
  {
    id: '2',
    name: 'New Beginning',
    emotion: 'Renewal',
    fragrance: 'Lemongrass Lime · Garden Mint',
    description: 'A bright citrus-mint candle made for fresh starts and new energy. Light, green, and alive — lemongrass and lime spark clarity while garden mint cools and resets the mind.',
    price: 35,
    image_url: '',
    badge: 'Renewal',
    burn_time: '~45–55 hrs',
    wax: 'Premium Blend',
    size: '7 oz / 198g',
    for_text: 'For new chapters, new homes, new mindsets. For anyone who has closed a door and is ready to open the next one.',
    care_notes: 'First day of a new month. After a big decision. Sunday mornings. Any moment you\'re consciously beginning again.',
  },
  {
    id: '3',
    name: 'You Are Enough',
    emotion: 'Self-Worth',
    fragrance: 'Papaya Paradise · Mango',
    description: 'A warm tropical candle that reminds you to feel whole, worthy, and enough. Sun-ripened papaya and mango create a soft, golden warmth — a scent that feels like a reminder: you have always been enough.',
    price: 35,
    image_url: '',
    badge: 'Self-Worth',
    burn_time: '~45–55 hrs',
    wax: 'Premium Blend',
    size: '7 oz / 198g',
    for_text: 'For moments of self-doubt, comparison, or exhaustion. For the nights you forget your own worth.',
    care_notes: 'Self-care rituals, evenings alone, after difficult conversations, or whenever you need a soft reminder.',
  },
]
