import type { Product } from '../types'

export const PRODUCTS: Product[] = [
  {
    id: '0',
    name: 'Let Go',
    emotion: 'Release',
    fragrance: 'Strawberry Guava · Coconut Lime · Verbena',
    description: 'A tropical-soft candle created to help you release, reset, and breathe again. This scent opens with fresh guava and ripe strawberry, softened by a coconut-lime base that dissolves tension and invites stillness.',
    price: 35,
    image_url: '/products/let-go.jpg',
    badge: 'Release',
    burn_time: '~45–55 hrs',
    wax: 'Premium Blend',
    size: '7 oz / 198g',
    for_text: 'For anyone holding on to something heavy — a feeling, a relationship, a version of themselves that no longer serves them.',
    care_notes: 'After a long day. In a bath. During journaling. Whenever you need permission to exhale.',
  },
  {
    id: '1',
    name: "I'm Safe",
    emotion: 'Safety',
    fragrance: 'Sea Salt · Orchid · Magnolia Peony',
    description: 'A clean floral-mineral scent for calm, safety, and quiet presence. Crisp sea salt grounds the blooming orchid and magnolia — a scent that feels like being held by something larger than yourself.',
    price: 35,
    image_url: '/products/im-safe.jpg',
    badge: 'Safety',
    burn_time: '~45–55 hrs',
    wax: 'Premium Blend',
    size: '7 oz / 198g',
    for_text: 'For the moments you need to feel safe, grounded, and at peace. For anxiety, uncertainty, or simply coming home to yourself.',
    care_notes: 'Morning rituals, meditation, creative work, or any moment that calls for presence and calm.',
  },
  {
    id: '2',
    name: 'New Beginning',
    emotion: 'Renewal',
    fragrance: 'Lemongrass Lime · Garden Mint',
    description: 'A bright citrus-mint candle made for fresh starts and new energy. Light, green, and alive — lemongrass and lime spark clarity while garden mint cools and resets the mind.',
    price: 35,
    image_url: '/products/new-beginning.jpg',
    badge: 'Renewal',
    burn_time: '~45–55 hrs',
    wax: 'Premium Blend',
    size: '7 oz / 198g',
    for_text: 'For new chapters, new homes, new mindsets. For anyone who has closed a door and is ready to open the next one.',
    care_notes: "First day of a new month. After a big decision. Sunday mornings. Any moment you're consciously beginning again.",
  },
  {
    id: '3',
    name: 'You Are Enough',
    emotion: 'Self-Worth',
    fragrance: 'Papaya Paradise · Mango · Jasmine',
    description: 'A warm tropical candle that reminds you to feel whole, worthy, and enough. Sun-ripened papaya and mango create a soft, golden warmth — a scent that feels like a reminder: you have always been enough.',
    price: 35,
    image_url: '/products/you-are-enough.jpg',
    badge: 'Self-Worth',
    burn_time: '~45–55 hrs',
    wax: 'Premium Blend',
    size: '7 oz / 198g',
    for_text: 'For moments of self-doubt, comparison, or exhaustion. For the nights you forget your own worth.',
    care_notes: 'Self-care rituals, evenings alone, after difficult conversations, or whenever you need a soft reminder.',
  },
]
